# Generated by Django 5.2.10 on 2026-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('users', '0003_remove_user_character_remove_user_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='street',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
