# Generated by Django 5.2.10 on 2026-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='style',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
