# Generated by Django 5.2.10 on 2026-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        (
            'quizzes',
            '0002_remove_quiz_answers_remove_quiz_street_delete_answer_and_more',
        ),
        ('users', '0003_remove_user_character_remove_user_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
