# Generated by Django 5.2.10 on 2026-04-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='character',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cities',
        ),
        migrations.DeleteModel(
            name='AnswerHistory',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
