# Generated by Django 5.2.10 on 2026-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_character_remove_user_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='final_character',
            field=models.JSONField(
                blank=True, null=True, verbose_name='Итоговый персонаж'
            ),
        ),
    ]
