# Generated by Django 5.2.10 on 2026-04-22 06:36

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_city_user_final_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='final_character',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                default='player',
                max_length=30,
                validators=[users.validators.RoleValidate],
            ),
        ),
    ]
