# Generated by Django 5.2.10 on 2026-04-22 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_final_character_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        verbose_name='Название результата',
                    ),
                ),
                (
                    'short_summary',
                    models.TextField(verbose_name='Краткий итог'),
                ),
                (
                    'snapshot',
                    models.JSONField(verbose_name='Снимок результата'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Дата создания',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='result_history',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'История прохождения',
                'verbose_name_plural': 'История прохождений',
                'ordering': ['-created_at'],
            },
        ),
    ]
