# Generated by Django 5.2.10 on 2026-04-22 10:28

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_change_cooldown_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                default='player',
                max_length=30,
                validators=[users.validators.RoleValidate()],
            ),
        ),
    ]
