# Generated by Django 5.2.10 on 2026-04-22 18:03

import core.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangecode',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AddField(
            model_name='passwordchangecode',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AddField(
            model_name='userresulthistory',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='expires_at',
            field=models.DateTimeField(
                default=core.models.default_expires_at,
                verbose_name='Срок действия',
            ),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='is_used',
            field=models.BooleanField(
                default=False, verbose_name='Использован'
            ),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='resend_available_at',
            field=models.DateTimeField(
                default=core.models.default_resend_available_at,
                verbose_name='Доступность повторной отправки',
            ),
        ),
        migrations.AlterField(
            model_name='passwordchangecode',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='passwordchangecode',
            name='expires_at',
            field=models.DateTimeField(
                default=core.models.default_expires_at,
                verbose_name='Срок действия',
            ),
        ),
        migrations.AlterField(
            model_name='passwordchangecode',
            name='is_used',
            field=models.BooleanField(
                default=False, verbose_name='Использован'
            ),
        ),
        migrations.AlterField(
            model_name='passwordchangecode',
            name='resend_available_at',
            field=models.DateTimeField(
                default=core.models.default_resend_available_at,
                verbose_name='Доступность повторной отправки',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                default='player',
                max_length=30,
                validators=[users.validators.RoleValidate()],
                verbose_name='Роль',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
    ]
