# Generated by Django 5.2.10 on 2026-04-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailchangecode_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
