# Generated by Django 5.2.10 on 2026-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchangecode',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='passwordchangecode',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
