# Generated by Django 5.2.10 on 2026-04-21 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuizSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'session_key',
                    models.CharField(db_index=True, max_length=40),
                ),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('final_character', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['session_key'],
                        name='analytics_c_session_80479a_idx',
                    ),
                    models.Index(
                        fields=['completed_at'],
                        name='analytics_c_complet_7610b1_idx',
                    ),
                ],
            },
        ),
    ]
