# Generated by Django 5.2.10 on 2026-04-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedquizsession',
            options={
                'verbose_name': 'Завершённая сессия теста',
                'verbose_name_plural': 'Завершённые сессии тестов',
            },
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='completed_at',
            field=models.DateTimeField(verbose_name='Завершение сессии'),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Создано'
            ),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(
                verbose_name='Длительность (сек)'
            ),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='final_character',
            field=models.JSONField(
                blank=True, null=True, verbose_name='Итоговый персонаж'
            ),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='session_key',
            field=models.CharField(
                db_index=True, max_length=40, verbose_name='Ключ сессии'
            ),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало сессии'),
        ),
        migrations.AlterField(
            model_name='completedquizsession',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
